// <auto-generated />
using System;
using EFCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreDefects.Model.FinancialsRevenue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FinancialsRevenue");
                });

            modelBuilder.Entity("EFCoreDefects.Model.PowerPurchaseAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FinancialsRevenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FinancialsRevenueId");

                    b.ToTable("PowerPurchaseAgreement");
                });

            modelBuilder.Entity("EFCoreDefects.Model.PowerPurchaseAgreement", b =>
                {
                    b.HasOne("EFCoreDefects.Model.FinancialsRevenue", null)
                        .WithMany("PowerPurchaseAgreements")
                        .HasForeignKey("FinancialsRevenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFCoreDefects.Model.Fid", "Fid", b1 =>
                        {
                            b1.Property<Guid>("PowerPurchaseAgreementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Fid");

                            b1.HasKey("PowerPurchaseAgreementId");

                            b1.ToTable("PowerPurchaseAgreement");

                            b1.WithOwner()
                                .HasForeignKey("PowerPurchaseAgreementId");
                        });

                    b.OwnsOne("EFCoreDefects.Model.PriceType", "PriceType", b1 =>
                        {
                            b1.Property<Guid>("PowerPurchaseAgreementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("PriceType");

                            b1.HasKey("PowerPurchaseAgreementId");

                            b1.ToTable("PowerPurchaseAgreement");

                            b1.WithOwner()
                                .HasForeignKey("PowerPurchaseAgreementId");
                        });

                    b.Navigation("Fid");

                    b.Navigation("PriceType");
                });

            modelBuilder.Entity("EFCoreDefects.Model.FinancialsRevenue", b =>
                {
                    b.Navigation("PowerPurchaseAgreements");
                });
#pragma warning restore 612, 618
        }
    }
}
